services:

  ms_address:
    image: address
    build:
      context: ./address
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/address_db?createDatabaseIfNotExist=true&serverTimezone=UTC&autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db_address
  
  ms_customer:
    image: customer
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/customer_db?createDatabaseIfNotExist=true&serverTimezone=UTC&autoReconnect=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db_customer

  db_address:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: address_db
    ports:
      - "3306:3306"

  db_customer:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
    ports:
      - "3306:3306"      