server:
  port: 8081
  servlet:
    context-path: /api/v1
  server-header: false
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    whitelabel:
      enabled: false
  tomcat:
    connection-timeout: 20000

debug: true

spring:
  application:
    name: address
  #  profiles:
  #    active: local # prod
  cache:
    type: simple
  gson:
    date-format: 'dd/MM/yyyy'
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    date-format: 'yyyy-MM-dd HH:mm:ss'
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
    time-zone: 'America/Sao_Paulo'
    locale: 'pt_BR'
  messages:
    encoding: UTF-8
    basename: "messages,config.i18n.messages"
    fallback-to-system-locale: true
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update # validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/address_db?createDatabaseIfNotExist=true&serverTimezone=UTC&autoReconnect=true
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      register-mbeans: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    repair: true
  cloud:
    discovery:
      enabled: true
    openfeign:
      client:
        default-config: true
      autoconfiguration:
        jackson:
          enabled: true

logging:
  config: classpath:logback-spring.xml
  charset: UTF-8
  include-application-name: true
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    br.com.juhmaran.address: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

via-cep:
  name: via-cep
  url: https://viacep.com.br/ws
